// Code generated by github.com/crowyy03/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: ref: refs/heads/add-mpl-grammar

package data

// linguist's commit from which files were generated.
var LinguistCommit = "ref: refs/heads/add-mpl-grammar"
